### ISSUE TITLE
AND - Phase Oracle on two QuantumBools behaving as different oracle

### ISSUE THREAD

**Issue by wzpxq** [fraunhoferfokus/Qrisp#2]
Running the following code

```
@auto_uncompute
def apply_phase_oracle_a_and_b(q): 
    temp_bool = (q[0] and q[1])
    z(temp_bool)

q = QuantumArray(qtype = QuantumBool(), shape = (2))
[h(i) for i in q]
apply_phase_oracle_a_and_b(q)
q.qs.statevector()
``` 

gives the following output 

$$\frac{|False\rangle |True\rangle + |False\rangle ^2 - |True\rangle |False\rangle - |True\rangle ^2} {2}$$ 

The minus sign before $|True\rangle |False\rangle$ should be a plus sign. 
As it is, the above oracle behaves as if
```
temp_bool = q[1] 
```

Other versions of a two-qubit oracle are also each working incorrectly: 
`temp_bool = q[0]` 
and 
`temp_bool = (q[0] or q[1])`

**Comment by positr0nium** [comment]
Hi,
[unfortunately it is not possible to overload the and operator.](https://peps.python.org/pep-0335/)

What you are looking for is 

`
q[0] & q[1]
`
or

`
q[0] | q[1]
`

**Comment by positr0nium** [comment]
You're right that would be very helpfull but as far as I know there is really no way to modify the behavior of these operators. There are a few other situations where the Python embedding prevents a more clean syntax - we could circumvent most of these, but as of right now I see no way around it.
We can add a warning in the QuantumBool documentation though.

**Comment by zickgraf** [comment]
Maybe you could overwrite `__bool__` to throw an error if the user attempts to use quantum variables as the left operand of `and` or `or`:

```python
class test:
    def __bool__(self):
        raise Exception("Conversion to boolean forbidden")

x = test()
y = test()

x and y
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __bool__
Exception: Conversion to boolean forbidden
```

**Comment by positr0nium** [comment]
With [0.2](https://www.qrisp.eu/general/changelog/0.2.html), the problem has been fixed and the proposed exception has been implemented.
